### ISSUE TITLE
Precomputed process tensors for performance testing

### ISSUE THREAD

**Issue by gefux** [tempoCollaboration/OQuPy#119]
To do performance testing efficiently it would be good to have a library of several precomputed process tensors.

I'd suggest that the generated process tensors should be stored on a public data record, (e.g. Zenodo) such that they can be loaded into /test/data/process_tensors when needed.

For a start we could generate process tensors that are a combination of

- Coupling strength alpha: 0.08 / 0.16 / 0.32
- Spectral density exponent: 1.0 / 3.0
- Temperature: 0.0 / 0.8 / 1.6 
- Cutoff: gauss
- dt: 0.02 / 0.04 / 0.08
- timesteps: 128 / 256

I'd imagine that the filenames then have a form like this example:
_boson_alpha0.16_zeta3.0_T0.8_gauss_dt0.04_step0128.hdf5_

What do you think @piperfw ?

**Comment by piperfw** [comment]
The suggested format seems sensible - I would probably use "gaussian" rather than "gauss" so as to match the named correlations parameter exactly (presumably a cutoff value should also be specified?).

My one question would be about the values of temperature and dt - do you have a reason for choosing those values? I would guess (T=0 and) the two being of similar scales would be reasonable.

**Comment by gefux** [comment]
> My one question would be about the values of temperature and dt - do you have a reason for choosing those values?

Yes, because those are the temperatures we chose for our paper on PT-TEBD (https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.5.033078). But I agree, for a start T=0.0 and T=0.8 would probably suffice.

**Comment by piperfw** [comment]
```python
fp = 'boson_alpha0.16_zeta3.0_T0.8_gauss_dt0.04_step0128.hdf5'
params = {key:float(val_str) for key,val_str in dict(re.findall('([a-zA-Z]*)([\d.]+)', os.path.splitext(fp)[0])).items()}
assert params['dt']*params['step'] == target_time # 5.12
```
:thinking: 

Powers of 2 works!

**Comment by piperfw** [comment]
Remaining discussion point is linking with Zenodo?
