### ISSUE TITLE
Typo in Tutorial Introduction

### ISSUE THREAD

**Issue by nelyasi** [tempoCollaboration/OQuPy#137]
I noticed a small typo in the tutorial's introduction section:

"optimize control protocols for non-Markovian open quantum systems [8,9],"
"compute the dynamics of a non-Markovian environment [10], and"
"obtain the thermal state of a strongly couled quantum system [11]."

The word "couled" should be "coupled" (missing the letter "P").

**Comment by piperfw** [comment]
Thanks @nelyasi, we'll make sure to fix that when the docs are next updated!

Appreciate the feedback and hope you are able to use the package successfully otherwise.

**Comment by piperfw** [comment]
Fixed with 38ae7c6 (ReadTheDocs should be updated in due course)
