### ISSUE TITLE
Typos In Readme.md

### ISSUE THREAD

**Issue by hmyuuu** [tempoCollaboration/OQuPy#143]
I noticed that there are some tiny typos in the links:https://github.com/tempoCollaboration/OQuPy/blob/38ae7c6bb61294cf6698a6792317b92310f5f7f1/README.md?plain=1#L38 https://github.com/tempoCollaboration/OQuPy/blob/38ae7c6bb61294cf6698a6792317b92310f5f7f1/README.md?plain=1#L41 https://github.com/tempoCollaboration/OQuPy/blob/38ae7c6bb61294cf6698a6792317b92310f5f7f1/README.md?plain=1#L43

It seems that there are extra `}`s, so the links can't be opened correctly.

**Comment by piperfw** [comment]
Well spotted @hmyuuu. Fixed these and in the docs (rebuilt) 359e9a0. Thanks for the contribution! 

[Aside @gefux pylint is failing due to too many positional arguments. I'll try to fix that now if not soon.]
