### ISSUE TITLE
Modify TEMPO & PT-TEMPO to only care about the subspace they couple to

### ISSUE THREAD

**Issue by gefux** [tempoCollaboration/OQuPy#29]
In the original [TEMPO publication](https://doi.org/10.1038/s41467-018-05617-3) Strathearn et al. have implemented TEMPO with a so-called degeneracy checking. This essentially restricts the influence funtionals to the dimension of the subspace which the coupling operator couples to. This can have huge computational advantages, particularly when the system is a bit larger (i.e. with Hilbertspace dimension > 3) Such a "degeneracy checking" would be nice to incorporate into this package as well.

**Comment by ewenlawrence** [comment]
Hi @gefux, I've had a look through the original publication and I think I have got this degeneracy checking working with a local copy of OQuPy. I have implemented this as a optional boolean variable when creating Tempo objects, which is then used to initialise two other attributes for the north south degeneracy and east west degeneracy (the same as the original code). These are then used as optional parameters in the infulence_matrix function, such that it is directly still compatible with previous code. The changes are then propagated through the backend code to ensure the correct summing vector etc. are used for each case.

Currently I've only made the TEMPO algorithm usable with the degeneracy checking (and will do this for PT as-well), but I assume that the non Markovian baths in the Mean field TEMPO can also use this trick, so I can also try implementing it there. If the structure of these changes seem reasonable to you and the other maintainers, I'll fork the repository and submit a pull request with my code for more detailed checks.

**Comment by gefux** [comment]
Hi @ewenlawrence,
This is great that you got that code working! Given that this might work for several other parts of the project as you mentioned, I think it would be worth having a chat over zoom (or some other platform) also with @piperfw if he is available. What do you think @piperfw?
If yes, would sometime next week work for you both? (We can agree on the details over email)

**Comment by piperfw** [comment]
That sounds really good, and I agree a chat would be valuable. I've good availability next week aside from Monday, let's arrange a time via email.

**Comment by ewenlawrence** [comment]
That sounds good, I'll send an email to the both of you and we can arrange a time for next week

**Comment by piperfw** [comment]
TEMPO degeneracy checking completed with #113 
Further testing and PT-TEMPO implementation discussion in #115
