### ISSUE TITLE
Quadrature and exact propagator construction for time dependent Hamiltonians

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#41]
Currently when constructing system propagators for a half timestep `[t, t+dt/2]` the integral of the system Hamiltonian `H(t)` (equivalently, Liouvillian) is approximated using a single point, `t+dt/4`. I have found integrating `H(t)` provides faster convergence with respect to `dt`; in my experience a gain (fewer influence tensors to compute) outweighing the cost of any numerical integration.

I therefore have two proposals:
1.  An option `subdiv_limit` to specify the number of subintervals used to integrate `H(t)` using quadratures (the current case corresponds to `subdiv_limit=1` and may be used as a default)
2.  The option to provide an anti-derivative for the Hamiltonian, in the case the time dependence of `H(t)` is simple and so the approximation can be skipped entirely

**Comment by gefux** [comment]
I believe you have something like this already in your mean-field code. Would you be happy to add this to the "regular" systems on the OQuPy-dev branch as well?

**Comment by piperfw** [comment]
I do, and it should carry directly over to regular systems just fine. Feel free to assign the issue to me.

One thing I want to check first was that the `limit` parameter of `scipy.quad_vec` (the analogue of `quad` for arrays) works as expected - for some reason a description of this parameter is omitted from [the function's documentation page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad_vec.html).

**Comment by piperfw** [comment]
I have reviewed this and think for direct interoperability with the current construction a simple method using `numpy.trapz` would be appropriate (rather than adaptive quadrature integration etc.). I will look to do this next week.

**Comment by piperfw** [comment]
Code for adaptive integration of the Liouvillian has been implemented for regular TimeDependSystems in PR #72. This is controlled by the `TempoParameters` `subdiv_limt` and `liouvillian_epsrel` (renamed from `hamiltonian_epsrel`): if `subdiv_limit` is `None` the system Liouvillain is sampled in order to construct the propagators, otherwise it and `liouvillian_epsrel` are passed to the quad function which integrates the Liouvillian over each half-timestep.

No `numpy.trapz` implementation has been provided.
Note the propagators are now provided by a `get_propagators` method of the System objects.
Note the default behaviour is to use quadratures to integrate the Liouvillian. We could make subdiv_limit default to `None` if we wanted to change this.

**Comment by piperfw** [comment]
Addressed by PR #72
