### ISSUE TITLE
Create a tutorial on how to use the Process Tensor (PT-TEMPO)

### ISSUE THREAD

**Issue by gefux** [tempoCollaboration/OQuPy#5]
In continuation of the quick start tutorial (which focuses on the conventional TEMPO), we should probably also have a  tutorial explaining how to use the process tensor approach to TEMPO.

**Comment by piperfw** [comment]
It would be good to include a couple of examples that illustrated why the process tensor approach can be useful (i.e. both 'how' and 'why' to use it). Perhaps setting up a bath and performing
- multiple runs with different parameters, where the System changes
- multiple runs with different measurements, where the Control changes

**Comment by gefux** [comment]
I assume the second tutorial I just added (2c3c7f0cba6b837c87c3c28fd081a36505cf38f9) does at least the first of the two points @piperfw mentions above.

**Comment by piperfw** [comment]
Second tutorial runs well and covers the first point above. Fixed some minor typos in #12 and suggested a rephrasing of the explanation of the PT which I think reads better but may or not emphasise what @gefux had in mind.

**Comment by gefux** [comment]
@piperfw , your suggested phrasing is much better, thank you! Also, apologies for the late merge - I've overlooked your request before.

**Comment by gefux** [comment]
Still left **ToDo**: (depending on #8)
Create a tutorial on how to use the process tensors with control operations.

**Comment by gefux** [comment]
I believe that this (_"Create a tutorial on how to use the process tensors with control operations."_) does not really need a separate tutorial. Feel free to reopen if you do!
