### ISSUE TITLE
Implement Control

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#8]
Both `Tempo` and `PtTempo` should be initialised with a (possibly trivial) `Control` object.

**Comment by gefux** [comment]
I agree on `Tempo`, however, I disagree on `PtTempo` as it is part of the point of process tensors that you can specify controls *after* computing the process tensor. `PtTempo` is just a tool to compute a process tensor.
(For others: See [[Pollock2018]](https://github.com/tempoCollaboration/TimeEvolvingMPO/blob/master/BIBLIOGRAPHY.md) for explanations on what controls and process tensors are in this context)

Which means: instead, I think, we'd like to have the following methods added to `ProcessTensor`:
-   `ProcessTensor.apply_system()`: This should return a process tensor, but now with the system Hamiltonian added to it (i.e. half a time step before the and half a time step after every slot)
-  `ProcessTensor.compute_scalar_from_control()`: This should return a complex number corresponding to the contraction of the process tensor with the inserted controls
- `ProcessTensor.compute_dynamics_from_control()`: This should return a dynamics object which is computed by with controls up to time t and just traces out later times (for each time t).

For all this, we'd need to create the `Control` object first, of course.

**Comment by gefux** [comment]
I've come to change my mind about the ProcessTensor methods above. I now think the process tensors really should only store the information of a process tensor. Computing the dynamics or correlations of a system should be a separate function which  takes a System, a Control and possibly multiple ProcessTensor(s).

**Back to the Control objects:**
The Control object should at least capture all possible control operations as introduced in [Pollock2018](http://dx.doi.org/10.1103/PhysRevA.97.012127). There the controls are a discrete finite set of CP maps---one for each time step. In addition to this I'd like that one can specify physically meaningful control operations independent of the choice of the time grid. Therefore i think a Control object should have the following three parts to it:

1. a discrete set of control operations for each time step (e.g a pi-pulse at step 6)
2. a discrete set of control operations for specific times (e.g. a pi-pulse at time 9.4)
3. a continuous control operation spanning a finite time (e.g. a Gaussian pi-pulse centred at time 10.0 with width 2.0)

For 1 and 2 it might be quite important whether the operation is performed just before or just after say step 6 (which then enters into the Dynamics object for example). Thus there should be a pre and post option.

Futhermore, it is in fact advantageous not to restrict the control operations to CP maps, but also allow to simply apply a left or right operator. Although the intermediate Dynamics objects will not represent density matrices anymore, with this one can directly compute complex valued multi-time correlations.

**Comment by gefux** [comment]
PR #38 realises the first two parts. The continuous control is still missing, the documentation and tests are still missing.

**Comment by gefux** [comment]
Single system controls are implemented and there appears to be no need for continuous controls so far. Hence I close this.
Followup issue for tests: #100
