### ISSUE TITLE
Read the docs outdated

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#82]
The Read the Docs page 'latest' appears to still be Oqupy ver. 0.3.3. In particular the mean-field tutorial notebook displayed is the version before the additions made for v0.4.0.

I don't think I have access to the project on Read the Docs.

**Comment by gefux** [comment]
Oh, yes. I've updated the read the docs page now and I'll contact you (@piperfw) through other channels to gain access.
