### ISSUE TITLE
Supply memory time instead of dkmax to TempoParameters

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#87]
Historically we've always set the bath memory cut-off via (`dt` and) an integer `dkmax`. 

Having an option to specify the bath cut-off time directly (`dkmax` calculated behind the scenes) may make more sense in many situations e.g. when varying `dt` to check for convergence whilst keeping the cut-off fixed.

**Comment by gefux** [comment]
I agree.

**Comment by piperfw** [comment]
Proposed changes:
- `tempo.TempoParameters` takes a parameter `tauc` (replacing `dkmax`), float or int
- a helper `_parse_tauc` returns the corresponding int `dkmax` to be used internally (i.e. the first `dkmax` such that `dt * dkmax >= tauc`)
- `tempo.guess_tempo_parameters` updated to return `tauc`
- all tutorials, examples and relevant tests will need to be updated

**Comment by piperfw** [comment]
Final implementation has both integer `dkmax` _and_ float `tcut` #88
