### ISSUE TITLE
Gibbs state tempo

### ISSUE THREAD

**Issue by aidanstrathearn** [tempoCollaboration/OQuPy#92]
Hi all,

It would be good to have an implementation of TEMPO for finding reduced gibbs states, as in PhysRevA.106.012204.

I think the main requirements are:

1. A backend that has the initial state state as an optional argument, with the initial input leg left dangling off the side of the propagated mps if no initial state given. This would also allow the standard TEMPO algorithm to have the option to calculate dynamical maps rather than just dynamics of an initial state (though maybe not as efficiently as PT-TEMPO).
2.  A new class in the tempo.py module using the new backend which will output a single density matrix representing the reduced gibbs state. Since the reduced gibbs state is nominally the steady state of standard TEMPO a nicer option might be to  implement it  as a 'compute_steady_state' method of the existing Tempo class.
3.  A correlations class which can handle imaginary time arguments.

I've made a start by creating a correlations class which lets you pass complex arguments to the bath correlation function, giving the same outputs as CustomSD when restricting to real time arguments.  It also calculates the eta coefficients without needing the integrand dictionary that CustomSD  uses.

My branch for this: https://github.com/aidanstrathearn/OQuPy/tree/gibbs_state 

Aidan

**Comment by gefux** [comment]
Implemented with #131
