### ISSUE TITLE
.readthedocs.yaml build.image deprecation warning

### ISSUE THREAD

**Issue by piperfw** [tempoCollaboration/OQuPy#97]
I have recently started receiving email notifications from `support@readthedocs.org` that the `build.image` config key on `.readthedocs.yaml` will be removed on Oct 16 2023 and that `oqupy` is impacted by this deprecation. `build.os` is the new alternative https://blog.readthedocs.com/use-build-os-config/

Our `.readthedocs.yaml` does not appear to use (or have ever used) the `build.image`, @gefux can you confirm that this does not affect us? Feel free to close this issue immediately in that case.

**Comment by gefux** [comment]
I'd be also confused by such a notification. I think there is no need to worry.

**Comment by piperfw** [comment]
Yup, sorry for the false alarm, seems like they are just mass mailing any project built within the last 3 years (poorly worded notification) https://github.com/readthedocs/readthedocs.org/pull/10589/commits/3d99b0bc5944777c32760f84f067fac7d0eb58d5
