### ISSUE TITLE
Check for h5py version

### ISSUE THREAD

**Issue by KristinBArnardottir** [tempoCollaboration/OQuPy#98]
I found that process_tensor.export(filename) didn't work out of the box for me with the pip install due to not having the correct h5py version installed. Once I updated to the latest version of h5py the export/import works well, even if the documentation isn't ready yet.

**Comment by piperfw** [comment]
Hi Kristin, thanks for raising this. `h5py` isn't specified in `requirements.txt` so I expect a recent update to the package or another package on PyPI has caused a compatibility issue.

Would you be able to share a minimal working example of it failing and the version of `h5py` that was present if you happen to still have access to that (`pip list` etc.)?

**Comment by KristinBArnardottir** [comment]
Hi Piper,

I know that at least one computer I was using had h5py 2.9.0 when it was giving an error.

Bellow is a full minimal working example, but in general it is the process tensor method export(filename) as well as the function import_process_tensor(filename) (if a file already exists).

`import oqupy

sigma_z = oqupy.operators.sigma("z")
correlations = oqupy.PowerLawSD(alpha=0.3,
                                zeta=1,
                                cutoff=5.0,
                                cutoff_type='exponential')
bath = oqupy.Bath(0.5 * sigma_z, correlations)
tempo_parameters = oqupy.TempoParameters(dt=0.1, dkmax=10, epsrel=10**(-4))

process_tensor = oqupy.pt_tempo_compute(bath=bath,
                                        start_time=0.,
                                        end_time=3.0,
                                        parameters=tempo_parameters)

process_tensor.export('PTfile.pt')`

**Comment by piperfw** [comment]
Thanks Kristin!

Just testing this in a fresh `python3.6` environment: `pip install oqupy` installed `h5py 3.1.0` which runs fine. That definitely makes the issue less critical as I think the minimal you can expect is for dependencies to work in a new environment. Still, it may be worth specifying a minimum `h5py` version. I'll step through a few versions now and see where things break.

**Comment by piperfw** [comment]
`h5py 3.1.0` is the last version supported by Python 6. Going back to `h5py 3.0.0` already breaks the export (`OSError`).

@gefux do you have any strong opinion on adding `h5py>=3.0.0` to the requirement files?

As an aside, it would be good to update the PyPI version of OQuPy as this still has the bug that prevents correlations being calculated for mean-field systems.

**Comment by piperfw** [comment]
Closed with 4e88c9b62191960a4b14d66163672bac422cdcca
